### ISSUE TITLE
Clover El Capitan – Time Lagging (delaying)

### ISSUE THREAD

**Issue by dj-sash** [Piker-Alpha/ssdtPRGen.sh#185]
Hello Pkier-Alpha,
I am not so new to hackintosh, and I have succeeded to fully install El Capitan. The only trouble I am having is the 'Time delay/lag'. About 20 seconds delay per minute. And all my system seems to be working slower, I know the real speed of my system. And this is a fresh new installation, it cannot lag so much.
I have an Intel Core 2 Duo E7400, Nvidia GeForce 9400GT 1024Mb and 4Gb DDR2 Ram 667 MHz.
I have used the Chris1111 Clover Legacy installation. Everything is working well, but DELAYING. Can you help me fix that?
And it is presenting my system as iMac (27-inch, late 2009)
I have tried adding what I have read in "config.plist" busratio=10.5   <<< but it did not solve anything in the time delay. I know this is an issue of matching the CPU clock speed, what it seems to me.
Wish to hear from you soon.
Thanks,
Nawaaz

**Comment by Piker-Alpha** [comment]
I'm not sure that I understand you, and without any data.... Let's see if I am reading this correctly. Your system clock is running too slow and the overal performance feels kind of sluggish. Like something is wrong. Did you install the Intel Power Gadget? If not please do so. It will show you what frequencies it is reaching. Let me know what you get.

**Comment by dj-sash** [comment]
No, I haven't installed the Power Gadget. And yes you are right by what you have understood. If I can add you on Skype or Hangouts. That would be easier to chat.

**Comment by dj-sash** [comment]
Is Power Gadget for Mac?

**Comment by dj-sash** [comment]
Power Gadget does not support my version of CPU, which is Intel Core 2 Duo.
It says not supported for my CPU.

**Comment by dj-sash** [comment]
If you wish to add me on Skype let me know. My id is illusion7_ltd
We can chat later there about that trouble. Thanks Piker-Alpha

**Comment by Piker-Alpha** [comment]
I prefer to help people here, when it fits me best.

Please add the command (arguments) you used to create your SSDT. This way I can verify it because like now. Without anything. I have no idea what you did.

**Comment by dj-sash** [comment]
Hello Pike. I have been able to fix the issue of TIME-Delay. Someone else
helped me on the insanelymac forum. I was just hesitating to add the
"BusSpeedKHz" in the config.plist. Ok this is solved.

Now I am having another issue. I am not being able to update my El Capitan.
I mean, right now I am 10.11 and I want to upgrade to 10.11.3, but I cannot.
I have downloaded the 10.11.3 Combo update. I am launching it, it is
launching well and restarting to update. Even the Apple logo + 21 minutes
remaining appears, it goes to 20 minutes. And the it SHUT DOWN.

Can you help me solving that update issue? Thanks and waiting for your help
in this.

**Comment by Piker-Alpha** [comment]
Ah ok. I think that I blogged about this bug [here](https://pikeralpha.wordpress.com/2015/12/29/skylake-bus-speed-tip/). Seems like that bug is still unfixed. Anyway. I guess that you got it sorted by adding 25MHz for the external frequency.

Sorry, but I cannot help you with installation issues. You have to look for help elsewhere. But the issue that you had is resolved now so lets close this issue.

**Comment by dj-sash** [comment]
Hello Pike. Good evening. I am facing a new issue. I am not sure if that is with the Hackintosh or with the Internet Provider. But, let me describe it to you.
I have a 10MB/s Fibre Optic connection. When I am browsing or watching Youtube, everything is working super fast. I am using iStat menu by which I can read the speed. But, when I am downloading the bandwidth is like being limited to maximum 35KB/s, All my downloads are being very slow (Mail, Safari downloads, Skype downloads). But, on the contrary while browsing the speed is OK.
I have been using the same built in Realtek-RTL8111C Gigabit LAN with the RealtekRTL8111.kext
I have hackintosh since Leopard till Yosemite. I have never faced such an issue.
Can you help me solving that?
Thanks
