### ISSUE TITLE
missing Processor

### ISSUE THREAD

**Issue by dhdhxk** [Piker-Alpha/ssdtPRGen.sh#301]
Hi.

Thanks for your works.

This does not work with my processor.

http://ark.intel.com/products/76640/Intel-Core-i5-4570R-Processor-4M-Cache-up-to-3_20-GHz

Can you check and talk to me why it happened?

Thanks.

**Comment by Piker-Alpha** [comment]
I added the missing processor data to Haswell.cfg Should work now. Please confirm.

**Comment by dhdhxk** [comment]
Hi. It still doesn`t work.

Can you check it for me?

Thanks.

**Comment by dhdhxk** [comment]
I got this message.

$ ./ssdtPRGen.sh 


ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen
             v15.6 Copyright (c) 2013-2016 by Pike R. Alpha
-----------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

gDataPath: /Users/gorilla13/Library/ssdtPRGen/Data
System information: Mac OS X 10.11.6 (15G31)
Brandstring 'Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz'

Error: Unknown processor model ...
       Visit http://ark.intel.com to gather the required data:
       Processor Number
       TDP
       Low Frequency Mode (use AppleIntelInfo.kext)
       Base Frequency
       Max Turbo Frequency
       Cores
       Threads
Aborting ...
Done.

**Comment by dhdhxk** [comment]
NVM. I succeed it.

Thanks!

**Comment by Piker-Alpha** [comment]
Ok. Cool. Closing issue.
